name: Upload SBOM to Dependency-Track
description: Uploads an SBOM to Dependency-Track using a Go CLI

inputs:
  dependency-track-url:
    description: 'Base URL of Dependency-Track instance'
    required: true
  dependency-track-key:
    description: 'API key for Dependency-Track'
    required: true
  project-name:
    description: 'Name of the project'
    required: true
  project-version:
    description: 'Version of the project'
    required: true
  parent-name:
    description: 'Optional parent project name'
    required: false
  is-latest:
    description: 'Whether to mark the version as latest (true/false)'
    required: false
    default: 'true'
  project-tags:
    description: 'Comma-separated project tags'
    required: false
  sbom-file:
    description: 'Path to the SBOM file to upload'
    required: false
  github-actor:
    description: 'Used for authenticating to GHCR. Commonly $\{{ github.actor }}'
    required: true
  github-token:
    description: 'Used for authenticating to GHCR. Commonly $\{{ secrets.GITHUB_TOKEN }}'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Build sbom-uploader Docker image
      run: docker pull ghcr.io/octopusdeploy/sbom-uploader-go:latest
      shell: bash

    - name: Run uploader container
      run: |
        docker run --rm \
          -e DEPENDENCY_TRACK_URL='${{ inputs.dependency-track-url }}' \
          -e DEPENDENCY_TRACK_KEY='${{ inputs.dependency-track-key }}' \
          -e PROJECT_NAME='${{ inputs.project-name }}' \
          -e PROJECT_VERSION='${{ inputs.project-version }}' \
          -e PROJECT_PARENT='${{ inputs.parent-name }}' \
          -e PROJECT_TAGS='${{ inputs.project-tags }}' \
          -v "${{ github.workspace }}/${{ inputs.sbom-file }}:/tmp/sbom.json" \
          ghcr.io/octopusdeploy/sbom-uploader-go:latest \
            --sbom /tmp/sbom.json \
            --latest=${{ inputs.is-latest }}
      shell: bash
