name: Build and Release SBOM Uploader

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.2.3

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist/
          OUTPUT=sbom-uploader-${GOOS}-${GOARCH}
          if [ "$GOOS" = "windows" ]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          go build -o dist/$OUTPUT ./main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: vars
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"


      - name: Build Docker image
        run: |
          docker build -t sbom-uploader-go:${{ steps.vars.outputs.VERSION }} .

      - name: Tag and Push to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/sbom-uploader-go
          docker tag sbom-uploader-go:${{ steps.vars.outputs.VERSION }} $IMAGE:${{ steps.vars.outputs.VERSION }}
          docker tag sbom-uploader-go:${{ steps.vars.outputs.VERSION }} $IMAGE:latest
          docker push $IMAGE:${{ steps.vars.outputs.VERSION }}
          docker push $IMAGE:latest

      - name: Save image as tar
        run: |
          docker save sbom-uploader-go:${{ steps.vars.outputs.VERSION }} -o dist/sbom-uploader-go.tar
          mkdir -p dist
          mv sbom-uploader-go.tar dist/

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: dist/sbom-uploader-go.tar


  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, docker]

    steps:
      - name: Download binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: release-assets/

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "SBOM Uploader ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
